name: Deploy React

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: docker build -t ahmedgamil/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true ahmedgamil/react-test npm run test
